// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           10
// Async Callback (empty):               1
// Total number of exported functions:  13

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    prediqs
    (
        init => init
        upgrade => upgrade
        addCategory => add_category
        toggleCategoryStatus => toggle_category_status
        createMarket => create_market
        cancelMarket => cancel_market
        resolveMarket => resolve_market
        placeBet => place_bet
        claimWinnings => claim_winnings
        claimRefund => claim_refund
        getMarket => get_market
        getAllCategories => get_all_categories
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
